In [1]:
import numpy as np

In [5]:
np.array( [1,2,3]  )   

array([1, 2, 3])

In [9]:
ang = np.array( [[1,2,3], [4,5,6] ] ) 
ang

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
ang.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
a = np.array ([[1,1] , [1,0]])
a

array([[1, 1],
       [1, 0]])

In [14]:
b = np.array ([[0,1] , [1,-1]])
b

array([[ 0,  1],
       [ 1, -1]])

In [21]:
c = a*b
d = c.T
d

array([[0, 1],
       [1, 0]])

In [45]:
%%timeit
s = 0
a ,b = 0,10000000
for x in range(a, b+1):
    s += x
s

611 ms ± 17.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [46]:
%%timeit
s = sum(range(a, b+1))


32.4 ms ± 604 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [47]:
%%timeit
s = (b+1-a) * (a+b) / 2.0

211 ns ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [53]:
x = 'Angela andy miao Frank umair ali saira arfa asma sajjad orange aple mango strawberry'

# total vowels in x
s = 0
for i in x:
    if i in 'AEIOUaeiou':
        s = s + 1
s 

31

In [54]:
# can you find how many non vowels are in ther


In [60]:
a = 0
for i in x:
    if i not in 'AEIOUaeiou':
        a = a + 1
a ,len(x)

(53, 84)

In [64]:
x
A,a,B,b,C,c,D,d,E,e,F,f,G,g,H,h,I,i,J,j,K,k,L,l,M,m,N,n,O,o,P,p,Q,q,R,r,S,s,T,t,U,u,V,v,W,w,X,x,Y,y,Z,z

NameError: name 'A' is not defined

In [66]:
x
# count unique charaters from x

'Angela andy miao Frank umair ali saira arfa asma sajjad orange aple mango strawberry'

In [67]:
banana = {}# [A,a,B,b,C,c,D,d,E,e,F,f,G,g,H,h,I,i,J,j,K,k,L,l,M,m,N,n,O,o,P,p,Q,q,R,r,S,s,T,t,U,u,V,v,W,w,X,x,Y,y,Z,z]
a = 0
for i in x:
    if i not in banana:
        banana[i] = 1
    else:
        banana[i] += 1
banana

{'A': 1,
 'n': 5,
 'g': 3,
 'e': 4,
 'l': 3,
 'a': 18,
 ' ': 13,
 'd': 2,
 'y': 2,
 'm': 4,
 'i': 4,
 'o': 3,
 'F': 1,
 'r': 8,
 'k': 1,
 'u': 1,
 's': 4,
 'f': 1,
 'j': 2,
 'p': 1,
 't': 1,
 'w': 1,
 'b': 1}

In [68]:
# find only vowels
x = [1,2,3,4,5,]